Tacten/biograph

healthcare/healthcare/doctype/patient/patient.js
healthcare/healthcare/doctype/patient_encounter/patient_encounter.js
healthcare/healthcare/doctype/patient_encounter/patient_encounter.py
healthcare/healthcare/doctype/patient_encounter_diagnosis/patient_encounter_diagnosis.json
healthcare/hooks.py
healthcare/public/js/healthcare_practitioner.js
healthcare/public/js/patient_quick_entry.js

Validation for phone and mobile fields: Alphabetic characters are not allowed.

---

healthcare/healthcare/doctype/patient/patient.json
healthcare/healthcare/doctype/patient_encounter/patient_encounter.js
healthcare/healthcare/doctype/patient_encounter/patient_encounter.json
healthcare/healthcare/doctype/patient_encounter/patient_encounter.py

Resolved :  https://github.com/Tacten/happiest_frappe/issues/35
To improve clarity and consistency, the following field names have been updated:
`patient_diagnosis` → `patient_medical_history`
`patient_medication` → `patient_medication_history`
`patient_surgery` → `patient_surgery_history`
The following custom fields have been removed and incorporated under the Patient DocType:
`custom_family_history` → `family_history`
`custom_social_history` → `social_history`
https://github.com/Tacten/happiest_frappe/pull/42
In above PR you can see other changes related this field

Implementation of patient load history in patient encounter

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

Fixed :  Notification will trigger on value change of status
Reason to fixed this issue :
```
appointment_doc = frappe.get_doc("Patient Appointment", appointment_id)
appointment_doc.status = "Cancelled"
appointment_doc.save()
```
When I used above method to update the status to `Cancelled`, the system updated another status according to the conditions in the [set_status](https://github.com/Tacten/biograph/blob/03cbdc11e236db555b49f5df69c9c0b324a0213f/healthcare/healthcare/doctype/patient_appointment/patient_appointment.py#L327) function, because there is no condition specified for the `Cancelled` status.

Fixed the status update issue for cancellation of appointment

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/patient_appointment/patient_appointment.json
healthcare/healthcare/doctype/patient_appointment/patient_appointment.py
healthcare/public/js/mark_unavailable.js
wiki/DESIGN-BLOCKBASED-THERAPY-APPOINTMENT-BOOKING.md

Block based appointment booking
The Block-Based Appointment System enhances Frappe Healthcare's appointment booking functionality by introducing a flexible time range booking approach for all appointment types. The system allows healthcare providers to book appointments using custom time ranges rather than fixed slots, providing greater scheduling flexibility while maintaining proper conflict management with existing appointments. This design maintains the familiar "Check Availability" entry point while adapting the dialog to support both traditional slot-based and the new block-time booking methods.
1. **Universal Dual Booking Modes**
- Slot-based: Traditional fixed-time slot booking 
- Block-time: Flexible time range booking available for all appointment types
- Toggle option to switch …

Block apmt

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/patient_appointment/patient_appointment.json
healthcare/healthcare/doctype/patient_appointment/patient_appointment.py
healthcare/healthcare/doctype/patient_appointment_therapy/patient_appointment_therapy.json

1. Remove Get Prescribed Therapies
2. Don't populate the Healthcare Practitioner 
3. Filter the Therapy types to show only the associated Therapy types of the Plan

Fixed the Patient Appointment and creation of therapy sessions

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/therapy_session/therapy_session.js
healthcare/healthcare/doctype/therapy_session/therapy_session.py

Fixed: stop wrong selection time in Appointment and wrong appointment in therapy session

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

Allow Conflict with Patient Appointment which is Closed

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/therapy_plan/therapy_plan.js
healthcare/healthcare/doctype/therapy_session/therapy_session.js
healthcare/healthcare/doctype/therapy_session/therapy_session.py

fixed the creation of session stop if the plan is completed

---

healthcare/healthcare/custom_doctype/sales_invoice.py
healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/patient_appointment/patient_appointment.py
healthcare/healthcare/doctype/patient_appointment_therapy/patient_appointment_therapy.json
healthcare/public/js/sales_invoice.js

PMS - 178
On change of Amount of Sales Invoice Payment table and on save system will throw the message
PMS - 172

Paid amount not allow to input more then invoice grand total

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js

Set the practitioner same as therapy plan 

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

Not allow to select a completed therapy plan

---

healthcare/healthcare/doctype/patient_assessment/patient_assessment.json

made the field read only to not allow select a date older or future

---

healthcare/healthcare/doctype/therapy_plan/therapy_plan.js
healthcare/healthcare/doctype/therapy_plan/therapy_plan.py

fixed the dashboard Amount issue on therapy plan

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

PMS 177 : Status should auto update open to "Confirm" for todays appointment

---

healthcare/healthcare/doctype/therapy_plan/therapy_plan.js

Create the Document From. The Create button only

Disabled the create options ( + ) in therapy plan Connection dashboard

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py
healthcare/healthcare/doctype/therapy_plan/therapy_plan.py
healthcare/healthcare/doctype/therapy_session/therapy_session.py

Validate if no of session exceeds
Appointment only allow if the thrapay type has some balance

validations of therapy sessions

---

healthcare/healthcare/custom_doctype/sales_invoice.py
healthcare/healthcare/utils.py
healthcare/public/js/sales_invoice.js

First Error fixed
Second Error:
while using a Healthcare Service options on Sales invoice Practitioner is not getting fetch

Fixed the error: while creating an sales invoice using get items from

---

healthcare/healthcare/doctype/healthcare_practitioner/healthcare_practitioner.py

Validate Schedules in practitioner : Schedule should be unique in the table

---

healthcare/healthcare/doctype/patient_assessment/patient_assessment.json
healthcare/public/js/form.js

Submitted message with the title or patient name

feat: submit pop up with title or patient name

---

healthcare/healthcare/utils.py
healthcare/public/js/sales_invoice.js

feat: Improve the dialog of get items from and added a date column

---

healthcare/healthcare/doctype/patient_encounter/patient_encounter.py

fixed : doctor template field was not searchable with diagnosis

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

[PAShttps://happiesthealth-dwh.atlassian.net/browse/PAS-259](https://happiesthealth-dwh.atlassian.net/browse/PAS-259)
https://happiesthealth-dwh.atlassian.net/browse/PAS-194

fix: missing service unit in case of therapy appointments

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py
healthcare/healthcare/doctype/service_request/service_request.js
healthcare/healthcare/doctype/service_request/service_request.py

Service Request creation for Referral Practitioner

---

healthcare/healthcare/doctype/appointment_type/appointment_type.json
healthcare/healthcare/doctype/patient_appointment/patient_appointment.json
healthcare/healthcare/doctype/patient_appointment/patient_appointment.py
healthcare/healthcare/doctype/patient_encounter/patient_encounter.js
healthcare/healthcare/doctype/patient_encounter/patient_encounter.json
healthcare/healthcare/doctype/patient_encounter/patient_encounter.py
healthcare/healthcare/doctype/service_request/service_request.js
healthcare/healthcare/doctype/service_request/service_request.py
healthcare/healthcare/doctype/therapy_plan/therapy_plan.js
healthcare/healthcare/doctype/therapy_plan/therapy_plan.json
healthcare/healthcare/doctype/therapy_session/therapy_session.js

Patient Referral Functionality and Clinical Note Functionality

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

https://happiesthealth-dwh.atlassian.net/browse/PAS-240

fix: change the format of error message

---

healthcare/healthcare/doctype/patient_encounter/patient_encounter.py
healthcare/public/js/healthcare_note.html

Timestamp Not Updating After Modifying Clinical Notes in Draft Patient Encounter

---

healthcare/healthcare/doctype/patient_assessment/patient_assessment.js
healthcare/healthcare/doctype/patient_assessment/patient_assessment.py

fix: error while score field value is missing in assessment sheet table

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.py

fix: appointment status issue

---

healthcare/healthcare/doctype/patient_appointment/recuring_appointment_handler.py
healthcare/public/js/recurring_appointments.js

Time selection validation
Message design for wrong slot selection
manage a load of server by screen freezing

fix: Recurring appointments enhancement

---

healthcare/healthcare/doctype/patient_appointment/patient_appointment.js
healthcare/healthcare/doctype/patient_encounter/patient_encounter.py

fix: conflict pop up was not appear
